{
 "title": "Flinox Dashboard",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated)"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}